import datetime

data_info = {
    "service_url": "https://line.botframework.com/",
    "channel_id": "line",
    "user_id": "Uddb46bdf5d17686fcacec3cb4381abca",
    "user_name": "許項涵 Shawn",
    "user_text": "這是Line哈哈哈哈",
    "bot_text": "機器人訊息",
    "feedback_status": 1,  # 0: 沒有提供問卷, 1: 提供問卷, 2: 填寫完畢,
    "feedback": {"bot": "你是否滿意？", "user": "滿意"},
    "user_timestmp": "",
    "bot_timestmp": "",
    "reference": [
        {
            "vector_id": "654a0390ac6ef25988505897",
            "document_id": "6549f7de451f6020fd8279be",
            "document_name": "共同學科暨通識教育中心 專任教師.docx",
            "document_source": "raw",
            "created_at": "2023-11-07T17:29:48.305+00:00",
        },
        {
            "vector_id": "...",
            "document_id": "...",
        },
        {
            "vector_id": "...",
            "document_id": "...",
        },
    ],
}


line_body = {
    "type": "message",
    "id": "EfcK4NpKN05",
    "timestamp": "2023-11-20T02:46:52.8017583Z",
    "serviceUrl": "https://line.botframework.com/",
    "channelId": "line",
    "from": {"id": "Uddb46bdf5d17686fcacec3cb4381abca", "name": "許項涵 Shawn"},
    "conversation": {
        "isGroup": False,
        "id": "Uddb46bdf5d17686fcacec3cb4381abca|D2qxSemfGiG",
    },
    "recipient": {"id": "D2qxSemfGiG", "name": "shawn-exp-bot"},
    "text": "這是Line哈哈哈哈",
    "channelData": {
        "message": {"text": "這是Line哈哈哈哈", "id": "482541434991018675", "type": "text"},
        "replyToken": "35c486b3079746b58cc430ce8eec6086",
        "type": "message",
        "source": {"type": "user", "userId": "Uddb46bdf5d17686fcacec3cb4381abca"},
        "timestamp": 1700448412270,
    },
}

line_activity = {
    "additional_properties": {},
    "type": "message",
    "id": "EfcK4NpKN05",
    "timestamp": datetime.datetime(2023, 11, 20, 2, 46, 52, 801758),
    "local_timestamp": None,
    "local_timezone": None,
    "service_url": "https://line.botframework.com/",
    "channel_id": "line",
    "from_property": {
        "additional_properties": {},
        "id": "Uddb46bdf5d17686fcacec3cb4381abca",
        "name": "許項涵 Shawn",
        "aad_object_id": None,
        "role": None,
    },
    "conversation": "<botbuilder.schema._models_py3.ConversationAccount object at 0x7f9b30c54e50>",
    "recipient": "<botbuilder.schema._models_py3.ChannelAccount object at 0x7f9b30c54ee0>",
    "text_format": None,
    "attachment_layout": None,
    "members_added": None,
    "members_removed": None,
    "reactions_added": None,
    "reactions_removed": None,
    "topic_name": None,
    "history_disclosed": None,
    "locale": None,
    "text": "這是Line哈哈哈哈",
    "speak": None,
    "input_hint": None,
    "summary": None,
    "suggested_actions": None,
    "attachments": None,
    "entities": None,
    "channel_data": {
        "message": {"text": "這是Line哈哈哈哈", "id": "482541434991018675", "type": "text"},
        "replyToken": "35c486b3079746b58cc430ce8eec6086",
        "type": "message",
        "source": {"type": "user", "userId": "Uddb46bdf5d17686fcacec3cb4381abca"},
        "timestamp": 1700448412270,
    },
    "action": None,
    "reply_to_id": None,
    "label": None,
    "value_type": None,
    "value": None,
    "name": None,
    "relates_to": None,
    "code": None,
    "expiration": None,
    "importance": None,
    "delivery_mode": None,
    "listen_for": None,
    "text_highlights": None,
    "semantic_action": None,
    "caller_id": "<CallerIdConstants.public_azure_channel: 'urn:botframework:azure'>",
}


teams_body = {
    "text": "[B9:46] Shawn\r\n這是Teams哈哈哈哈",
    "textFormat": "plain",
    "attachments": [
        {
            "contentType": "text/html",
            "content": '<p style="margin-bottom:0px; margin-left:0; margin-top:0px"><span style="font-size:inherit">[B9:46] Shawn</span></p>\r\n<p><span style="font-size:inherit">這是Teams哈哈哈哈</span></p>',
        }
    ],
    "type": "message",
    "timestamp": "2023-11-20T02:52:53.1885541Z",
    "localTimestamp": "2023-11-20T10:52:53.1885541+08:00",
    "id": "1700448773174",
    "channelId": "msteams",
    "serviceUrl": "https://smba.trafficmanager.net/apac/",
    "from": {
        "id": "29:1f6MnElOr3a_lNnoI6V2t1f2wl5GLT4T741Fjt-o6EPrO4_TzlRmbo_yCKoAjCIgJyQl1bXNbsqqoGKkHyQ5uAA",
        "name": "Shawn",
        "aadObjectId": "1ed6c7ae-70f3-458b-9c4a-629605764085",
    },
    "conversation": {
        "conversationType": "personal",
        "tenantId": "d1b8065f-067c-4b46-9992-0699c696d252",
        "id": "a:1yFtu-I_HS-WVl_aJ3Uy65V24wdg-NTWY-bXeEAsYr4i6l_olYe1r4prwDbUF8tshw_YODf_vRN6GkcVr7qCT10RwyasuAK1JYwqdhoPYq1IAyjwELiRJs9gCSInhRcHp",
    },
    "recipient": {
        "id": "28:5cf7ee2e-77df-4a36-a31c-c5bf5f029f18",
        "name": "shawn-exp-bot",
    },
    "entities": [
        {
            "locale": "zh-TW",
            "country": "TW",
            "platform": "Mac",
            "timezone": "Asia/Taipei",
            "type": "clientInfo",
        }
    ],
    "channelData": {"tenant": {"id": "d1b8065f-067c-4b46-9992-0699c696d252"}},
    "locale": "zh-TW",
    "localTimezone": "Asia/Taipei",
}


teams_activity = {
    "additional_properties": {},
    "type": "message",
    "id": "1700448773174",
    "timestamp": datetime.datetime(2023, 11, 20, 2, 52, 53, 188554),
    "local_timestamp": datetime.datetime(2023, 11, 20, 10, 52, 53, 188554),
    "local_timezone": "Asia/Taipei",
    "service_url": "https://smba.trafficmanager.net/apac/",
    "channel_id": "msteams",
    "from_property": {
        "additional_properties": {},
        "id": "29:1f6MnElOr3a_lNnoI6V2t1f2wl5GLT4T741Fjt-o6EPrO4_TzlRmbo_yCKoAjCIgJyQl1bXNbsqqoGKkHyQ5uAA",
        "name": "Shawn",
        "aad_object_id": "1ed6c7ae-70f3-458b-9c4a-629605764085",
        "role": None,
    },
    "conversation": "<botbuilder.schema._models_py3.ConversationAccount object at 0x7f9b10049430>",
    "recipient": "<botbuilder.schema._models_py3.ChannelAccount object at 0x7f9b100494c0>",
    "text_format": "plain",
    "attachment_layout": None,
    "members_added": None,
    "members_removed": None,
    "reactions_added": None,
    "reactions_removed": None,
    "topic_name": None,
    "history_disclosed": None,
    "locale": "zh-TW",
    "text": "[B9:46] Shawn\r\n這是Teams哈哈哈哈",
    "speak": None,
    "input_hint": None,
    "summary": None,
    "suggested_actions": None,
    "attachments": [
        "<botbuilder.schema._models_py3.Attachment object at 0x7f9b10033a30>"
    ],
    "entities": ["<botbuilder.schema._models_py3.Entity object at 0x7f9b100337c0>"],
    "channel_data": {"tenant": {"id": "d1b8065f-067c-4b46-9992-0699c696d252"}},
    "action": None,
    "reply_to_id": None,
    "label": None,
    "value_type": None,
    "value": None,
    "name": None,
    "relates_to": None,
    "code": None,
    "expiration": None,
    "importance": None,
    "delivery_mode": None,
    "listen_for": None,
    "text_highlights": None,
    "semantic_action": None,
    "caller_id": "<CallerIdConstants.public_azure_channel: 'urn:botframework:azure'>",
}


web_body = {
    "type": "message",
    "id": "3QWgrFHLX5QLr0uVLqsqzX-as|0000002",
    "timestamp": "2023-11-20T03:01:49.8552634Z",
    "localTimestamp": "2023-11-20T11:01:49.782+08:00",
    "localTimezone": "Asia/Taipei",
    "serviceUrl": "https://webchat.botframework.com/",
    "channelId": "webchat",
    "from": {"id": "1ed6c7ae-70f3-458b-9c4a-629605764085", "name": ""},
    "conversation": {"id": "3QWgrFHLX5QLr0uVLqsqzX-as"},
    "recipient": {"id": "shawn-exp-bot@qn6go_jj_sQ", "name": "shawn-exp-bot"},
    "textFormat": "plain",
    "locale": "zh-TW",
    "text": "這是Web哈哈哈哈",
    "attachments": [],
    "channelData": {"clientActivityID": "170044930978197yqqp4j06a"},
}

web_activity = {
    "additional_properties": {},
    "type": "message",
    "id": "3QWgrFHLX5QLr0uVLqsqzX-as|0000002",
    "timestamp": datetime.datetime(2023, 11, 20, 3, 1, 49, 855263),
    "local_timestamp": datetime.datetime(2023, 11, 20, 11, 1, 49, 782000),
    "local_timezone": "Asia/Taipei",
    "service_url": "https://webchat.botframework.com/",
    "channel_id": "webchat",
    "from_property": {
        "additional_properties": {},
        "id": "1ed6c7ae-70f3-458b-9c4a-629605764085",
        "name": "",
        "aad_object_id": None,
        "role": None,
    },
    "conversation": "<botbuilder.schema._models_py3.ConversationAccount object at 0x7f9b180193d0>",
    "recipient": "<botbuilder.schema._models_py3.ChannelAccount object at 0x7f9b18019ee0>",
    "text_format": "plain",
    "attachment_layout": None,
    "members_added": None,
    "members_removed": None,
    "reactions_added": None,
    "reactions_removed": None,
    "topic_name": None,
    "history_disclosed": None,
    "locale": "zh-TW",
    "text": "這是Web哈哈哈哈",
    "speak": None,
    "input_hint": None,
    "summary": None,
    "suggested_actions": None,
    "attachments": [],
    "entities": None,
    "channel_data": {"clientActivityID": "170044930978197yqqp4j06a"},
    "action": None,
    "reply_to_id": None,
    "label": None,
    "value_type": None,
    "value": None,
    "name": None,
    "relates_to": None,
    "code": None,
    "expiration": None,
    "importance": None,
    "delivery_mode": None,
    "listen_for": None,
    "text_highlights": None,
    "semantic_action": None,
    "caller_id": "<CallerIdConstants.public_azure_channel: 'urn:botframework:azure'>",
}
